version: '3.8'

services:
  postgres12:
    image: postgres:12
    container_name: postgres12
    restart: unless-stopped
    environment:
      POSTGRES_USER: pg12_user
      POSTGRES_PASSWORD: pg12_password
      POSTGRES_DB: pg12_db
    ports:
      - "5432:5432"
    volumes:
      - pg12:/var/lib/postgresql/data

  postgres15:
    image: postgres:15
    container_name: postgres15
    restart: unless-stopped
    depends_on:
      - postgres12    
    environment:
      POSTGRES_USER: pg15_user
      POSTGRES_PASSWORD: pg15_password
      POSTGRES_DB: pg15_db
    # Using port 5433 to avoid port collisions on localhost
    ports:
      - "5433:5432"
    volumes:
      - pg15:/var/lib/postgresql/data      

  spree_api:
    image: massdrivercloud/rails-spree-example
    container_name: spree_api
    restart: always
    depends_on:
      - postgres12
    ports:
      - "4000:4000"
    environment:
      # DATABASE_URL: postgres://pg12_user:pg12_password@postgres12:5432/store
      DATABASE_URL: postgres://pg15_user:pg15_password@postgres15:5432/store
      SECRET_KEY_BASE: foobar
      LOG_LEVEL: error
      PORT: 4000
    entrypoint: bundle
    command: [exec, rails, server]
  
  # ## Uncomment if you need to reseed the database
  # job_spree_seed:
  #   image: massdrivercloud/rails-spree-example
  #   container_name: job_spree_seed
  #   depends_on:
  #     - postgres12
  #   volumes:
  #     - ./spree-seed-job.sh:/entrypoint.sh
  #   environment:
  #     DATABASE_URL: postgres://pg12_user:pg12_password@postgres12:5432/store
  #     SECRET_KEY_BASE: foobar
  #     ADMIN_EMAIL: test@example.com
  #     ADMIN_PASSWORD: password!    
  #   entrypoint: ["/bin/sh","/entrypoint.sh"]    

volumes:
  pg12:
  pg15:
